/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
  'recipientUsername' : IDL.Text,
});
export const ConversationSummary = IDL.Record({
  'username' : IDL.Text,
  'lastMessage' : IDL.Opt(Message),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'isBanned' : IDL.Bool,
  'banExpiryTimestamp' : IDL.Int,
  'myBucksBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'enhanceWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'getAllConversationsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationWithToken' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getLatestUnreadMessageSenderWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMyBucksBalanceWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUnreadMessageCountWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'logoutToken' : IDL.Func([IDL.Text], [], []),
  'markMessageAsReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'registerWithToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBySerial' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'username' : IDL.Text, 'displayName' : IDL.Text })],
      ['query'],
    ),
  'sendMessageWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'terminateWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unbanWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDisplayNameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePasswordWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUsernameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
    'recipientUsername' : IDL.Text,
  });
  const ConversationSummary = IDL.Record({
    'username' : IDL.Text,
    'lastMessage' : IDL.Opt(Message),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'isBanned' : IDL.Bool,
    'banExpiryTimestamp' : IDL.Int,
    'myBucksBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'enhanceWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'getAllConversationsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationWithToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getLatestUnreadMessageSenderWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMyBucksBalanceWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUnreadMessageCountWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'logoutToken' : IDL.Func([IDL.Text], [], []),
    'markMessageAsReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'registerWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBySerial' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'username' : IDL.Text, 'displayName' : IDL.Text })],
        ['query'],
      ),
    'sendMessageWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'terminateWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unbanWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDisplayNameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePasswordWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateUsernameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };