/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
  'recipientUsername' : IDL.Text,
});
export const ConversationSummary = IDL.Record({
  'username' : IDL.Text,
  'lastMessage' : IDL.Opt(Message),
});
export const AdminUserInfo = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'isBanned' : IDL.Bool,
  'banExpiryTimestamp' : IDL.Int,
  'passwordHash' : IDL.Text,
  'myBucksBalance' : IDL.Nat,
});
export const CallStatus = IDL.Variant({
  'ringing' : IDL.Null,
  'ended' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
export const CallSession = IDL.Record({
  'id' : IDL.Text,
  'status' : CallStatus,
  'startedAt' : IDL.Int,
  'endedAt' : IDL.Int,
  'callType' : CallType,
  'sdpOffer' : IDL.Opt(IDL.Text),
  'callerUsername' : IDL.Text,
  'callerIceCandidates' : IDL.Vec(IDL.Text),
  'answeredAt' : IDL.Int,
  'calleeIceCandidates' : IDL.Vec(IDL.Text),
  'calleeUsername' : IDL.Text,
  'sdpAnswer' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'isBanned' : IDL.Bool,
  'banExpiryTimestamp' : IDL.Int,
  'myBucksBalance' : IDL.Nat,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
  'recipientUsername' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIceCandidateWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminRemoveMyBucksWithToken' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'answerCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'declineCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMessageWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'endCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'enhanceWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'getAllConversationsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getAllUsersWithPasswords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdminUserInfo)],
      ['query'],
    ),
  'getCallSessionWithToken' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CallSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationWithToken' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getIncomingCallWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CallSession)],
      ['query'],
    ),
  'getLatestUnreadMessageSenderWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMyBucksBalanceWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getNotificationsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getUnreadMessageCountWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'impersonateSendWithToken' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'initiateCallWithToken' : IDL.Func(
      [IDL.Text, CallType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'logoutToken' : IDL.Func([IDL.Text], [], []),
  'markMessageAsReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'markNotificationReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'registerWithToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'removeConversationWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBySerial' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'username' : IDL.Text, 'displayName' : IDL.Text })],
      ['query'],
    ),
  'sendMessageWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendSdpAnswerWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendSdpOfferWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendSystemNotificationWithToken' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'terminateWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unbanWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDisplayNameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePasswordWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUsernameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
    'recipientUsername' : IDL.Text,
  });
  const ConversationSummary = IDL.Record({
    'username' : IDL.Text,
    'lastMessage' : IDL.Opt(Message),
  });
  const AdminUserInfo = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'isBanned' : IDL.Bool,
    'banExpiryTimestamp' : IDL.Int,
    'passwordHash' : IDL.Text,
    'myBucksBalance' : IDL.Nat,
  });
  const CallStatus = IDL.Variant({
    'ringing' : IDL.Null,
    'ended' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
  const CallSession = IDL.Record({
    'id' : IDL.Text,
    'status' : CallStatus,
    'startedAt' : IDL.Int,
    'endedAt' : IDL.Int,
    'callType' : CallType,
    'sdpOffer' : IDL.Opt(IDL.Text),
    'callerUsername' : IDL.Text,
    'callerIceCandidates' : IDL.Vec(IDL.Text),
    'answeredAt' : IDL.Int,
    'calleeIceCandidates' : IDL.Vec(IDL.Text),
    'calleeUsername' : IDL.Text,
    'sdpAnswer' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'isBanned' : IDL.Bool,
    'banExpiryTimestamp' : IDL.Int,
    'myBucksBalance' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
    'recipientUsername' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIceCandidateWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminRemoveMyBucksWithToken' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'answerCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'declineCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMessageWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'endCallWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'enhanceWithToken' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'getAllConversationsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getAllUsersWithPasswords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdminUserInfo)],
        ['query'],
      ),
    'getCallSessionWithToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CallSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationWithToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getIncomingCallWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CallSession)],
        ['query'],
      ),
    'getLatestUnreadMessageSenderWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMyBucksBalanceWithToken' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getNotificationsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUnreadMessageCountWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'impersonateSendWithToken' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'initiateCallWithToken' : IDL.Func(
        [IDL.Text, CallType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'logoutToken' : IDL.Func([IDL.Text], [], []),
    'markMessageAsReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'markNotificationReadWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'registerWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'removeConversationWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBySerial' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'username' : IDL.Text, 'displayName' : IDL.Text })],
        ['query'],
      ),
    'sendMessageWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendSdpAnswerWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendSdpOfferWithToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendSystemNotificationWithToken' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'terminateWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unbanWithToken' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDisplayNameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePasswordWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateUsernameWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };