/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationSummary {
  'username' : string,
  'lastMessage' : [] | [Message],
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'senderUsername' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'recipientUsername' : string,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'serialNumber' : bigint,
  'isBanned' : boolean,
  'banExpiryTimestamp' : bigint,
  'myBucksBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banWithToken' : ActorMethod<[bigint, bigint, string], undefined>,
  'enhanceWithToken' : ActorMethod<[bigint, bigint, string], undefined>,
  'getAllConversationsWithToken' : ActorMethod<
    [string],
    Array<ConversationSummary>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationWithToken' : ActorMethod<[string, string], Array<Message>>,
  'getLatestUnreadMessageSenderWithToken' : ActorMethod<
    [string],
    [] | [string]
  >,
  'getMyBucksBalanceWithToken' : ActorMethod<[string], bigint>,
  'getUnreadMessageCountWithToken' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUsername' : ActorMethod<[string], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithToken' : ActorMethod<[string, string, string], UserProfile>,
  'logoutToken' : ActorMethod<[string], undefined>,
  'markMessageAsReadWithToken' : ActorMethod<[bigint, string], undefined>,
  'registerWithToken' : ActorMethod<[string, string, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBySerial' : ActorMethod<
    [bigint],
    { 'username' : string, 'displayName' : string }
  >,
  'sendMessageWithToken' : ActorMethod<[string, string, string], undefined>,
  'terminateWithToken' : ActorMethod<[bigint, string], undefined>,
  'unbanWithToken' : ActorMethod<[bigint, string], undefined>,
  'updateDisplayNameWithToken' : ActorMethod<[string, string], undefined>,
  'updatePasswordWithToken' : ActorMethod<[string, string, string], undefined>,
  'updateUsernameWithToken' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];