/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserInfo {
  'username' : string,
  'displayName' : string,
  'serialNumber' : bigint,
  'isBanned' : boolean,
  'banExpiryTimestamp' : bigint,
  'passwordHash' : string,
  'myBucksBalance' : bigint,
}
export interface CallSession {
  'id' : string,
  'status' : CallStatus,
  'startedAt' : bigint,
  'endedAt' : bigint,
  'callType' : CallType,
  'sdpOffer' : [] | [string],
  'callerUsername' : string,
  'callerIceCandidates' : Array<string>,
  'answeredAt' : bigint,
  'calleeIceCandidates' : Array<string>,
  'calleeUsername' : string,
  'sdpAnswer' : [] | [string],
}
export type CallStatus = { 'ringing' : null } |
  { 'ended' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type CallType = { 'video' : null } |
  { 'voice' : null };
export interface ConversationSummary {
  'username' : string,
  'lastMessage' : [] | [Message],
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'senderUsername' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'recipientUsername' : string,
}
export interface Notification {
  'id' : bigint,
  'text' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'recipientUsername' : string,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'serialNumber' : bigint,
  'isBanned' : boolean,
  'banExpiryTimestamp' : bigint,
  'myBucksBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIceCandidateWithToken' : ActorMethod<[string, string, string], undefined>,
  'adminRemoveMyBucksWithToken' : ActorMethod<
    [bigint, bigint, string],
    undefined
  >,
  'answerCallWithToken' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banWithToken' : ActorMethod<[bigint, bigint, string], undefined>,
  'declineCallWithToken' : ActorMethod<[string, string], undefined>,
  'deleteMessageWithToken' : ActorMethod<[bigint, string], undefined>,
  'endCallWithToken' : ActorMethod<[string, string], undefined>,
  'enhanceWithToken' : ActorMethod<[bigint, bigint, string], undefined>,
  'getAllConversationsWithToken' : ActorMethod<
    [string],
    Array<ConversationSummary>
  >,
  'getAllUsersWithPasswords' : ActorMethod<[string], Array<AdminUserInfo>>,
  'getCallSessionWithToken' : ActorMethod<[string, string], [] | [CallSession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationWithToken' : ActorMethod<[string, string], Array<Message>>,
  'getIncomingCallWithToken' : ActorMethod<[string], [] | [CallSession]>,
  'getLatestUnreadMessageSenderWithToken' : ActorMethod<
    [string],
    [] | [string]
  >,
  'getMyBucksBalanceWithToken' : ActorMethod<[string], bigint>,
  'getNotificationsWithToken' : ActorMethod<[string], Array<Notification>>,
  'getUnreadMessageCountWithToken' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUsername' : ActorMethod<[string], UserProfile>,
  'impersonateSendWithToken' : ActorMethod<
    [bigint, bigint, string, string],
    undefined
  >,
  'initiateCallWithToken' : ActorMethod<[string, CallType, string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithToken' : ActorMethod<[string, string, string], UserProfile>,
  'logoutToken' : ActorMethod<[string], undefined>,
  'markMessageAsReadWithToken' : ActorMethod<[bigint, string], undefined>,
  'markNotificationReadWithToken' : ActorMethod<[bigint, string], undefined>,
  'registerWithToken' : ActorMethod<[string, string, string, string], bigint>,
  'removeConversationWithToken' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBySerial' : ActorMethod<
    [bigint],
    { 'username' : string, 'displayName' : string }
  >,
  'sendMessageWithToken' : ActorMethod<[string, string, string], undefined>,
  'sendSdpAnswerWithToken' : ActorMethod<[string, string, string], undefined>,
  'sendSdpOfferWithToken' : ActorMethod<[string, string, string], undefined>,
  'sendSystemNotificationWithToken' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'terminateWithToken' : ActorMethod<[bigint, string], undefined>,
  'unbanWithToken' : ActorMethod<[bigint, string], undefined>,
  'updateDisplayNameWithToken' : ActorMethod<[string, string], undefined>,
  'updatePasswordWithToken' : ActorMethod<[string, string, string], undefined>,
  'updateUsernameWithToken' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];