/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CallSession {
    id: string;
    status: CallStatus;
    startedAt: bigint;
    endedAt: bigint;
    callType: CallType;
    sdpOffer?: string;
    callerUsername: string;
    callerIceCandidates: Array<string>;
    answeredAt: bigint;
    calleeIceCandidates: Array<string>;
    calleeUsername: string;
    sdpAnswer?: string;
}
export interface Message {
    id: bigint;
    text: string;
    senderUsername: string;
    isRead: boolean;
    timestamp: bigint;
    recipientUsername: string;
}
export interface ConversationSummary {
    username: string;
    lastMessage?: Message;
}
export interface UserProfile {
    username: string;
    displayName: string;
    serialNumber: bigint;
    isBanned: boolean;
    banExpiryTimestamp: bigint;
    myBucksBalance: bigint;
}
export enum CallStatus {
    ringing = "ringing",
    ended = "ended",
    accepted = "accepted",
    declined = "declined"
}
export enum CallType {
    video = "video",
    voice = "voice"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addIceCandidateWithToken(callId: string, candidate: string, token: string): Promise<void>;
    answerCallWithToken(callId: string, token: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banWithToken(serial: bigint, days: bigint, token: string): Promise<void>;
    declineCallWithToken(callId: string, token: string): Promise<void>;
    deleteMessageWithToken(messageId: bigint, token: string): Promise<void>;
    endCallWithToken(callId: string, token: string): Promise<void>;
    enhanceWithToken(serial: bigint, amount: bigint, token: string): Promise<void>;
    getAllConversationsWithToken(token: string): Promise<Array<ConversationSummary>>;
    getCallSessionWithToken(callId: string, token: string): Promise<CallSession | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversationWithToken(otherUsername: string, token: string): Promise<Array<Message>>;
    getIncomingCallWithToken(token: string): Promise<CallSession | null>;
    getLatestUnreadMessageSenderWithToken(token: string): Promise<string | null>;
    getMyBucksBalanceWithToken(token: string): Promise<bigint>;
    getUnreadMessageCountWithToken(token: string): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfileByUsername(username: string): Promise<UserProfile>;
    initiateCallWithToken(calleeUsername: string, callType: CallType, token: string): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    loginWithToken(username: string, passwordHash: string, sessionToken: string): Promise<UserProfile>;
    logoutToken(sessionToken: string): Promise<void>;
    markMessageAsReadWithToken(messageId: bigint, token: string): Promise<void>;
    registerWithToken(username: string, passwordHash: string, displayName: string, sessionToken: string): Promise<bigint>;
    removeConversationWithToken(otherUsername: string, token: string): Promise<void>;
    saveCallerUserProfile(arg0: UserProfile): Promise<void>;
    searchBySerial(serial: bigint): Promise<{
        username: string;
        displayName: string;
    }>;
    sendMessageWithToken(recipientUsername: string, text: string, token: string): Promise<void>;
    sendSdpAnswerWithToken(callId: string, sdp: string, token: string): Promise<void>;
    sendSdpOfferWithToken(callId: string, sdp: string, token: string): Promise<void>;
    terminateWithToken(serial: bigint, token: string): Promise<void>;
    unbanWithToken(serial: bigint, token: string): Promise<void>;
    updateDisplayNameWithToken(newDisplayName: string, token: string): Promise<void>;
    updatePasswordWithToken(currentPasswordHash: string, newPasswordHash: string, token: string): Promise<void>;
    updateUsernameWithToken(newUsername: string, token: string): Promise<void>;
}
import type { CallSession as _CallSession, CallStatus as _CallStatus, CallType as _CallType, ConversationSummary as _ConversationSummary, Message as _Message, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addIceCandidateWithToken(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIceCandidateWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIceCandidateWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async answerCallWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.answerCallWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerCallWithToken(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banWithToken(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async declineCallWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineCallWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineCallWithToken(arg0, arg1);
            return result;
        }
    }
    async deleteMessageWithToken(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageWithToken(arg0, arg1);
            return result;
        }
    }
    async endCallWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endCallWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endCallWithToken(arg0, arg1);
            return result;
        }
    }
    async enhanceWithToken(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enhanceWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enhanceWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllConversationsWithToken(arg0: string): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversationsWithToken(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversationsWithToken(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallSessionWithToken(arg0: string, arg1: string): Promise<CallSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallSessionWithToken(arg0, arg1);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallSessionWithToken(arg0, arg1);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversationWithToken(arg0: string, arg1: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationWithToken(arg0, arg1);
            return result;
        }
    }
    async getIncomingCallWithToken(arg0: string): Promise<CallSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingCallWithToken(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingCallWithToken(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestUnreadMessageSenderWithToken(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestUnreadMessageSenderWithToken(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestUnreadMessageSenderWithToken(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBucksBalanceWithToken(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBucksBalanceWithToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBucksBalanceWithToken(arg0);
            return result;
        }
    }
    async getUnreadMessageCountWithToken(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessageCountWithToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessageCountWithToken(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByUsername(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByUsername(arg0);
            return result;
        }
    }
    async initiateCallWithToken(arg0: string, arg1: CallType, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateCallWithToken(arg0, to_candid_CallType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateCallWithToken(arg0, to_candid_CallType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginWithToken(arg0: string, arg1: string, arg2: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async logoutToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutToken(arg0);
            return result;
        }
    }
    async markMessageAsReadWithToken(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsReadWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsReadWithToken(arg0, arg1);
            return result;
        }
    }
    async registerWithToken(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithToken(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithToken(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async removeConversationWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeConversationWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeConversationWithToken(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchBySerial(arg0: bigint): Promise<{
        username: string;
        displayName: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBySerial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBySerial(arg0);
            return result;
        }
    }
    async sendMessageWithToken(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async sendSdpAnswerWithToken(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSdpAnswerWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSdpAnswerWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async sendSdpOfferWithToken(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSdpOfferWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSdpOfferWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async terminateWithToken(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.terminateWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.terminateWithToken(arg0, arg1);
            return result;
        }
    }
    async unbanWithToken(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanWithToken(arg0, arg1);
            return result;
        }
    }
    async updateDisplayNameWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayNameWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayNameWithToken(arg0, arg1);
            return result;
        }
    }
    async updatePasswordWithToken(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePasswordWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePasswordWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUsernameWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsernameWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsernameWithToken(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CallSession_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallSession): CallSession {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CallType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallType): CallType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationSummary_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): ConversationSummary {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallSession]): CallSession | null {
    return value.length === 0 ? null : from_candid_CallSession_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    lastMessage: [] | [_Message];
}): {
    username: string;
    lastMessage?: Message;
} {
    return {
        username: value.username,
        lastMessage: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastMessage))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CallStatus;
    startedAt: bigint;
    endedAt: bigint;
    callType: _CallType;
    sdpOffer: [] | [string];
    callerUsername: string;
    callerIceCandidates: Array<string>;
    answeredAt: bigint;
    calleeIceCandidates: Array<string>;
    calleeUsername: string;
    sdpAnswer: [] | [string];
}): {
    id: string;
    status: CallStatus;
    startedAt: bigint;
    endedAt: bigint;
    callType: CallType;
    sdpOffer?: string;
    callerUsername: string;
    callerIceCandidates: Array<string>;
    answeredAt: bigint;
    calleeIceCandidates: Array<string>;
    calleeUsername: string;
    sdpAnswer?: string;
} {
    return {
        id: value.id,
        status: from_candid_CallStatus_n10(_uploadFile, _downloadFile, value.status),
        startedAt: value.startedAt,
        endedAt: value.endedAt,
        callType: from_candid_CallType_n12(_uploadFile, _downloadFile, value.callType),
        sdpOffer: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sdpOffer)),
        callerUsername: value.callerUsername,
        callerIceCandidates: value.callerIceCandidates,
        answeredAt: value.answeredAt,
        calleeIceCandidates: value.calleeIceCandidates,
        calleeUsername: value.calleeUsername,
        sdpAnswer: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.sdpAnswer))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ringing: null;
} | {
    ended: null;
} | {
    accepted: null;
} | {
    declined: null;
}): CallStatus {
    return "ringing" in value ? CallStatus.ringing : "ended" in value ? CallStatus.ended : "accepted" in value ? CallStatus.accepted : "declined" in value ? CallStatus.declined : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    voice: null;
}): CallType {
    return "video" in value ? CallType.video : "voice" in value ? CallType.voice : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Array<ConversationSummary> {
    return value.map((x)=>from_candid_ConversationSummary_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CallType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): _CallType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): {
    video: null;
} | {
    voice: null;
} {
    return value == CallType.video ? {
        video: null
    } : value == CallType.voice ? {
        voice: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
